### ISSUE TITLE
Dynamic require() in the worker

### ISSUE THREAD

**Issue by snajjar** [mapbox/workerpoolify#7]
Hello,

Following https://github.com/substack/webworkify/issues/34 here

I've adapted my code to workerpoolify, but i'm hitting the exact same problem here:

The worker works fine when i'm doing some basic require:
`var m = require('my-module');`

But if i want to resolve a module dynamically:
`
var a = 'my-module';
var m = require(a);
`

It issues a "MODULE_NOT_FOUND" error, even though the module is defined in the bundle (with working require() calls). How can i make dynamic require() with workerpoolify?

Can you please explain how are the worker module dependencies managed? Is there a way i can modify the code (of workerpoolify or webworkify) to include all the modules loaded in the bundle?

ps: please don't close the thread yet

**Comment by snajjar** [comment]
Hello,

I finally hacked this in webworkify. I think it would be a valuable feature to have an extra option parameter to include every source from the bundle in the worker.

Thread can be closed, if you want :)

**Comment by mourner** [comment]
Ah, I misunderstood the original issue. Workerpoolify resolves all dependencies at compile time, it just doesn't evaluate them on the worker side until they are used.
